### ISSUE TITLE
[docs] Add section to User Guide with ./destroy.sh instructions

### ISSUE THREAD

**Issue by eaberman** [GoogleCloudPlatform/stackdriver-sandbox#134]
In order for users to complete their use of Stackdriver Sandbox without incurring additional billing, it is important for the users to run the ./destroy.sh script at the end of their use.

However, the User Guide does not currently have a section instructing users to do so. A section near the end of the User Guide (before the OpenTelemetry section) could be added instructing users to do so.

**Comment by simonz130** [comment]
@eaberman, when submitting PR that fixes a bug, add *fixes #XXX* in the PR description. This will make sure the bug will be closed automatically as soon as your PR is committed.

**Comment by eaberman** [comment]
Okay, I will be sure to do that in the future.
