### ISSUE TITLE
Move stackdriver-sandbox.dev webpage off of github master branch

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/stackdriver-sandbox#187]
Currently stackdriver-sandbox.dev points to the content of the docs folder in the master branch. Whenever we make a change there, it's reflected on the website immediately. This prevents us from making incremental improvements that should not be visible to external customers until the release happens.

We should address that by pointing stackdriver-sandbox.dev to a hosted version of the website on AppEngine or somewhere else on GCP.

**Comment by Daniel-Sanche** [comment]
In the short term we could create a `gh_pages` branch to hold our website state, if you're worried about it getting out of sync. I'll also look into something like Cloud Run or AppEngine though

**Comment by simonz130** [comment]
I think we should host it on AppEngine instance on our stackdriver-sandbox project.
