### ISSUE TITLE
More than one matching billing account found

### ISSUE THREAD

**Issue by hsachdevah** [GoogleCloudPlatform/stackdriver-sandbox#19]
Getting this error while running terraform install script

* data.google_billing_account.acct: data.google_billing_account.acct: More than one matching billing account found

**Comment by hsachdevah** [comment]
Found why the error: I have two different billing accounts with the same name (ofcourse with different billing account id), one is active and the other one is closed.

**Comment by jiang95-dev** [comment]
Can anyone reproduce the error? I can't create a billing account with the existing name, even one is closed and one is active.

**Comment by simonz130** [comment]
Does it work if you have two billing accounts (even with different names)?

**Comment by jiang95-dev** [comment]
Yes. The only thing is it will make you choose which account you want to use.

**Comment by jiang95-dev** [comment]
This problem should have been addressed before, because we are using a filter for active billing accounts.
