### ISSUE TITLE
Ability to create into existing project.

### ISSUE THREAD

**Issue by charles-bluett** [GoogleCloudPlatform/stackdriver-sandbox#193]
In the case of my environment I would need to be able to install to a pre created project.

I just edited the terraform and the shell script and was able to get it working anyway.

**Comment by simonz130** [comment]
Fair point. We are adding state management in terraform provisioning. This will allow getting back to previous sandbox. This partially will solve the problem. However I can also see it being useful to create a sandbox in existing project.
