### ISSUE TITLE
logging: istio installation reports failure (maybe unnecessarily?)

### ISSUE THREAD

**Issue by gzhao408** [GoogleCloudPlatform/stackdriver-sandbox#225]
Upon running `./install.sh`, when it begins istio installation:

TLDR: The log says `Failed` and prints lots of stuff, suggesting that something has failed, then says it `Trying with...` and then `Istio 1.6.2 Download Complete!` 

My initial guess is that it's trying two different methods and reporting when the first one didn't work, which is misleading (users might think something went wrong unnecessarily). Then, I'd suggest making this log less verbose.

Another could be that something actually failed (it doesn't seem this way to me) - then this is a deeper issue.

Full log of what I'm talking about:

```bash
null_resource.install_istio: Creating...
null_resource.install_istio: Provisioning with 'local-exec'...
null_resource.install_istio (local-exec): Executing: ["/bin/sh" "-c" "./istio/install_istio.sh"]
null_resource.install_istio (local-exec): ###
null_resource.install_istio (local-exec): ### Begin install istio control plane
null_resource.install_istio (local-exec): ###
null_resource.install_istio (local-exec): Downloading Istio 1.6.2...
null_resource.install_istio (local-exec):   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
null_resource.install_istio (local-exec):                                  Dload  Upload   Total   Spent    Left  Speed
null_resource.install_istio (local-exec):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.install_istio (local-exec):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.install_istio (local-exec):   0  3896    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.install_istio (local-exec): 100  3896  100  3896    0     0   6334      0 --:--:-- --:--:-- --:--:-- 3804k
null_resource.install_istio (local-exec): Downloading istio-1.6.2 from https://github.com/istio/istio/releases/download/1.6.2/istio-1.6.
2-linux.tar.gz ...
null_resource.install_istio (local-exec): Failed.
null_resource.install_istio (local-exec): Trying with TARGET_ARCH. Downloading istio-1.6.2 from https://github.com/istio/istio/releases/
download/1.6.2/istio-1.6.2-linux-amd64.tar.gz ...
null_resource.install_istio (local-exec): Istio 1.6.2 Download Complete!
null_resource.install_istio (local-exec): Istio has been successfully downloaded into the istio-1.6.2 folder on your system.
```

**Comment by Daniel-Sanche** [comment]
The errors are coming from the [getLatestIstio script](https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCandidate.sh), which we don't own. It seems like the error message is an expected part of the script. The script prints everything to standard output, so our only options are to suppress all logs from the script, or show them all.

I think it should be fine to suppress this script's logs since it's fairly simple and reliable. But I also think it's not a huge problem to be overly verbose on a developer facing project

**Comment by nicklin37** [comment]
I agree it's possible for us to suppress the logs from this script, but my only concern is that it would also suppress the logs from applying the Istio Operator and istio-manifests which might be useful to know if both steps were completely successful. 

In Terraform the null resource won't complain if our script fails so if we attempted to apply a nonexistent operator then the null resource would still complete

**Comment by Daniel-Sanche** [comment]
Well we could just replace[ this line](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/45aa131ea4f565a9b087fc96c1d30fad7bd680d6/terraform/istio/install_istio.sh#L33) with: 

`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=$ISTIO_VERSION sh - > /dev/null`

That would silence just the getLatestIstio script. But still, not sure how worthwhile that is. Maybe it's still useful to see those logs?

**Comment by nicklin37** [comment]
I'll defer to Dan and Simon on this - I think seeing the logs might still be useful. Hopefully since the script continues on then users won't be convinced that Istio download failed.

**Comment by nicklin37** [comment]
Closing this for now since it seems like we still do want the logs - if there is strong support for silencing these logs then I'll reopen.
