### ISSUE TITLE
Cloud Shell images aren't updated on each commit

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/stackdriver-sandbox#227]
I believe this is being worked on, but adding an issue just in case

We [build and push new tagged images](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/master/.github/workflows/push-master.yml) for all services on each push to master. We should do the same with the new Cloud Shell image

**Comment by eaberman** [comment]
This is connected to the issue in which ./install.sh is not running. Updating the image on each commit would create an opportunity to correct the empty Dockerfile in GCR that is being used to build a custom image.
