### ISSUE TITLE
Install.sh is not run automatically

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/stackdriver-sandbox#233]
When running the [Open in Cloud Shell button](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/stackdriver-sandbox.git&cloudshell_working_dir=terraform&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image) with the custom image, it doesn't run install.sh automatically. Wasn't that one of the goals?

**Comment by eaberman** [comment]
This seems to stem from an issue in GCP: a build trigger builds a new image from an empty Dockerfile and replaces the image built from Dockerfile in GitHub repo.

The temporary fix is to push a new image, and to use the version-tagged image for "Open in Cloud Shell" command.

The longer-term solution is to correct the build trigger to build the image from the Dockerfile in the GitHub repo.
