### ISSUE TITLE
Reusing existing Sandbox should check tfstate before using

### ISSUE THREAD

**Issue by nicklin37** [GoogleCloudPlatform/stackdriver-sandbox#267]
When a user attempts to reuse a pre-existing Sandbox

Then the install script should check the GCS bucket and verify that the tfstate file is still valid to be used (i.e. the Sandbox is not out of date)

Otherwise it should reject the request and create a new one.

**Comment by jiang95-dev** [comment]
Due to the rebranding, we don't need to take care of the logic now.
