### ISSUE TITLE
Error reading Project "stackdriver-sandbox-4086952698": googleapi: Error 403: The caller does not have permission, forbidden

### ISSUE THREAD

**Issue by yurigrinshteyn** [GoogleCloudPlatform/stackdriver-sandbox#30]
Full Cloud Shell output:

./install.sh 
Checking Prerequisites...
Checking for billing accounts
using billing account: Personal Billing Account
Make sure Terraform is installed
Initialize terraform state

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
* provider.null: version = "~> 2.1"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Apply Terraform automation
null_resource.customize_manifests: Refreshing state... [id=8555647629071790355]
data.google_billing_account.acct: Refreshing state...
random_id.project: Refreshing state... [id=85ny-g]
google_project.project: Refreshing state... [id=stackdriver-sandbox-4086952698]
Error: Error reading Project "stackdriver-sandbox-4086952698": googleapi: Error 403: The caller does not have permission, forbidden

**Comment by simonz130** [comment]
I think the reason for this is that you already had a folder with cloned sandbox code and terraform stored state in that folder, so sandbox installation assumed some of that state and it caused errors. I'm looking at best way to address that, but for now the workaround would be always cloning into a separate, new folder.

**Comment by yurigrinshteyn** [comment]
Confirmed that `rm -rf` on the folder, cloning the repo again, and re-running install.sh was successful.  Thank you.
