### ISSUE TITLE
Stackdriver Dashboard URI should contain projectID

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/stackdriver-sandbox#33]
When creating a new Sandbox, the instructions contain a list of URLs of "next steps".
In dashboard URI, we need to add a **project** parameter so the link opens correctly.
https://app.google.stackdriver.com/accounts/create?**project=<CREATED_PROJECT?>**

**Comment by nicklin37** [comment]
Resolved in PR #57
