### ISSUE TITLE
Enable API and set-up billing as part of Sandbox provisioning

### ISSUE THREAD

**Issue by eaberman** [GoogleCloudPlatform/stackdriver-sandbox#46]
When setting up Stackdriver Debugger [following the steps in the Sandbox User Guide](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/master/docs/README.md#download-source-code), I receive a message asking whether I would like to enable the API in the cloud shell.

![Screenshot 2020-06-30 at 6 41 32 PM](https://user-images.githubusercontent.com/38052620/86618278-40131b80-bf7e-11ea-80bb-509f08544956.png)

This is a step that could be done as a part of Sandbox provisioning.

**Note:** following the choice to enable the API, in order to continue, the user must enable billing specifically for an API method called. If the API is enabled, it would be helpful to either add instructions to the User Guide specifying that API billing should be set-up, or find a way to do it automatically. Screenshot for this is shown below.

The earlier billing is enabled, the better, since it can take a few minutes for the system to register the updated billing information before the user can move on to the next step.
![Screenshot 2020-07-01 at 10 22 49 AM](https://user-images.githubusercontent.com/38052620/86618521-b021a180-bf7e-11ea-8115-48f7ff06a844.png)

**Comment by simonz130** [comment]
@jiang95-dev - this should be an easy fix - PTAL

**Comment by simonz130** [comment]
@jiang95-dev what is the current status of it? I don't see any PRs linked to this bug
