### ISSUE TITLE
docs: Error Reporting not as instructive as it could be

### ISSUE THREAD

**Issue by gzhao408** [GoogleCloudPlatform/stackdriver-sandbox#49]
The [Error Reporting](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/368ac9071949fe26b0434daf7a84f47b1e0bba9b/docs/README.md#stackdriver-error-reporting) section has two issues:
1. It seems that we need to manually enable the Error Reporting API to get it to work. This should be added to the instructions in the docs.
2. This demonstration would be more powerful if the user were able to manufacture some errors and see them reported on the UI. The docs could have some "how to break it" instructions, e.g. stopping nodes through the GCP console or a particular pattern using the load generator.

**Comment by simonz130** [comment]
We should not be manually enabling Error Reporting API. It should be done by the provisioning script. I'll open a separate issue on this.

For your second point, please open up a separate issue - we should add instructions on how to break things so folks will see errors in Error Reporting. @gzhao408

**Comment by gzhao408** [comment]
Closing in favor of #53
