### ISSUE TITLE
Add Istio to a hipstershop deployment on a Sandbox 

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/stackdriver-sandbox#50]
We need to add istio support, but likely having Anthos Service Mesh is even better option to illustrate how it helps observe the apps.

**Comment by Daniel-Sanche** [comment]
ASM looks like it requires an Anthos subscription. I think we'd be better off using OSS Istio for now. We can use this as a template: https://github.com/GoogleCloudPlatform/bank-of-anthos-scripts/blob/master/install/istio/install_istio.sh

**Comment by Daniel-Sanche** [comment]
Discussed this with Nick, he's going to try handling this, and we'll check back in next week.

Nick:
- [Here's how](https://github.com/GoogleCloudPlatform/microservices-demo#option-4-deploying-on-a-istio-enabled-gke-cluster) we added Istio upstream, but that method is stuck at 1.4, so we're better off using the OSS directions instead
- [This is a script](https://github.com/GoogleCloudPlatform/bank-of-anthos-scripts/blob/master/install/istio/install_istio.sh) we used to enable Istio 1.6 in a different project
- [This looks like](https://github.com/GoogleCloudPlatform/gke-anthos-holistic-demo/tree/master/holistic-demo/istio) another attempt to provision istio using terraform, but I'm not familiar enough with Terraform to say if it's useful for us

Let me know if you run into any issues

**Comment by nicklin37** [comment]
This has been resolved in #139
