### ISSUE TITLE
Enable Error Reporting API as part of provisioning script

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/stackdriver-sandbox#51]
We need to manually enable the Error Reporting API to get it to work in Sandbox. This should be automatically enabled by the provisioning

**Comment by jiang95-dev** [comment]
Error Reporting API is actually enabled in the script. The page doesn't show up in the Cloud Console because we are not reporting any errors explicitly in our demo code so the module never gets an input. This issue has been converted to #131.
